server:
  port: 8084

spring:
  application:
    name : MyService
   
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          
      show-sql: true
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sampleschema?autoReconnect=true&verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
    password: 1234   

service:
  retry:
    maxretryCount: 3
    retryDelay: 100
 
enrichment:
  retry:
    count: 10
    
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 70000
            
    getValue:
      circuitBreaker:
        requestVolumeThreshold: 20
        sleepWindowInMilliseconds: 50000

circuit:
  collapser:
    maxrequestsinbatch: 4
    timerdelayinmilliseconds: 500
                   

